# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67178c7c411bca0ab66357348acbbb7fbbe352ddb5bc8e36d3753d6e6ee28135d4a18f01ea1dd1675652c3d1c113a330c85da83e98d13d3fda98af4d642aaaa4

test:
  secret_key_base: 4cf46417c80fbf26f257fe153a92b569551b907e37f35619d0b50b01c6e984265bac77e4708ac17f2b0298c4f233f3ce1da3f7b13781ed29535fb1bb2f0a67dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
